LINK ERROR.
~/Desktop/biopencil> zig build
MachO Flush... warning(link): found dylib is incompatible with the required minimum version
warning(link):   dylib: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
warning(link):   required minimum version: 65536
warning(link):   dylib version: 0
error(link): unhandled symbol type: absolute
error(link):   symbol 'F_0_344'
error(link):   first definition in '/usr/local/Cellar/jpeg-turbo/2.1.4/lib/libjpeg.a(jdcolor-avx2.asm.o)'
error: UnhandledSymbolType
error: biopencil...
error: The following command exited with error code 1: